ros__parameters:
  common:
      lid_topic: None  # to be replaced in launch file with drone_id
      imu_topic: None  # to be replaced in launch file with drone_id 
      time_offset_lidar_imu: 0.0
      drone_id: None  # to be replaced in launch file with drone_id

  multiuav:
      cluster_extraction_in_predict_region: true
      inten_threshold: 1000
      ground_height_threshold: -0.6  # remove all points below this height (meter)
      min_high_inten_cluster_size: 4
      min_cluster_size: 3 # Unused
      predict_region_radius: 0.7
      temp_predict_region_radius: 0.7
      traj_matching_start_thresh: 15.0
      ave_match_error_thresh: 0.2
      pos_num_in_traj: 200
      reset_tracker_thresh: 5.0
      valid_cluster_size_thresh: 0.15
      valid_cluster_dist_thresh: 0.35
      mutual_observe_noise: 0.01
      frame_num_in_sliding_window: 1
      actual_uav_num: 4
      degeneration_thresh: 3.0

  imu_propagate:
      enable: false
      topic: "lidar_slam/imu_propagate"
      filter_acc_en: false

  preprocess:
      lidar_type: 6
      feature_extract_en: false
      scan_line: 6
      blind: 0.2

  calibration:
      cut_frame_en: false
      cut_frame_num: 1
      accumulate_frame_en: true  # Unused
      original_frequency: 10 # hz
      gravity_align_enable: true
      gravity_align_time: 5.0 # seconds
      PX4_R_I: [ 0.0, 0.0, 0.0 ] # degree
      PX4_p_I: [ 0.0, 0.0, 0.0 ] # meter
      level_horizon: [ 0.0 ,0.0 ,0.0 ] #degree

  mapping:
      imu_en: true  # Unused
      acc_cov: 0.01
      gyr_cov: 0.01
      b_acc_cov: 0.001
      b_gyr_cov: 0.001
      det_range: 20.0
      LI_extrinsic_T: [ 0.0, 0.0, -0.08 ]
      LI_extrinsic_R: [ 1.0, 0.0, 0.0,
                        0.0, 1.0, 0.0,
                        0.0, 0.0, 1.0]
      point_filter_num: 3
      max_iteration: 3
      filter_size_surf: 0.3
      filter_size_map: 0.5
      cube_side_length: 2000.0

  publish:
      path_en:  true
      scan_publish_en:  true       # false: close all the point cloud output
      dense_publish_en: false       # false: low down the points number in a global-frame point clouds scan.
      scan_bodyframe_pub_en: false  # true: output the point cloud scans in IMU body frame

  pcd_save:
      pcd_save_en: true
      pcd_resolution: 0.9
      interval: -1                 # how many LiDAR frames saved in each pcd file;
                                   # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
